# Generated by Django 4.0.2 on 2022-04-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileemployee',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.city'),
        ),
    ]
