# Generated by Django 4.0.2 on 2022-05-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nobat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moshavere.nobat'),
        ),
        migrations.AlterField(
            model_name='moshaverprofile',
            name='nobat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.nobat'),
        ),
    ]
