# Generated by Django 4.0.2 on 2022-05-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moshavere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meli_code', models.IntegerField(blank=True, unique=True)),
                ('student_number', models.IntegerField(blank=True, unique=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.city')),
                ('daneshjoo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('daneshkadeh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.daneshkadeh')),
                ('moshaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.moshaverprofile')),
            ],
        ),
    ]
