# Generated by Django 4.0.2 on 2022-04-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0002_marakezmoshavere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marakezmoshavere',
            old_name='markaz_name',
            new_name='daneshgah_name',
        ),
    ]
