# Generated by Django 4.0.2 on 2022-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0002_remove_employee_email_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('مشاور', 'مشاور'), ('ناظر', 'ناظر')], default='ناظر', max_length=8),
        ),
    ]
