# Generated by Django 4.0.2 on 2022-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='meli_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_number',
            field=models.IntegerField(unique=True),
        ),
    ]
