# Generated by Django 4.0.2 on 2022-05-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0002_reservation_nobat_alter_moshaverprofile_nobat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshaverprofile',
            name='nobat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.days'),
        ),
    ]
