# Generated by Django 4.0.2 on 2022-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0003_alter_reservation_meli_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='meli_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student_number',
            field=models.IntegerField(),
        ),
    ]
