# Generated by Django 4.0.2 on 2022-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0003_alter_moshaverprofile_nobat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moshaverprofile',
            old_name='nobat',
            new_name='roozhaye_hozor',
        ),
        migrations.AddField(
            model_name='consulation',
            name='nobat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
