# Generated by Django 4.0.2 on 2022-05-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0004_rename_nobat_moshaverprofile_roozhaye_hozor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moshaverprofile',
            name='roozhaye_hozor',
        ),
        migrations.AddField(
            model_name='moshaverprofile',
            name='roozhaye_hozor',
            field=models.ManyToManyField(to='moshavere.Days'),
        ),
    ]
