# Generated by Django 4.0.2 on 2022-04-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0004_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
    ]
