# Generated by Django 4.0.2 on 2022-05-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moshavere', '0004_alter_reservation_meli_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.city'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='daneshjoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='daneshkadeh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshavere.daneshkadeh'),
        ),
    ]
