# Generated by Django 4.0.2 on 2022-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0005_remove_moshaverprofile_roozhaye_hozor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
