# Generated by Django 4.0.2 on 2022-04-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0005_rename_cities_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='marakezmoshavere',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moshavere.city'),
        ),
    ]
