# Generated by Django 4.0.2 on 2022-04-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0006_marakezmoshavere_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daneshkadeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('saghfe_mojaz_hafte', models.IntegerField(default=0)),
                ('hours_weekly_authorized', models.IntegerField(default=0)),
                ('type_hamkari_ba_daneshgah', models.CharField(choices=[('مدعو', 'مدعو'), ('رسمی', 'رسمی'), ('پروژه ای', 'پروژه ای'), ('قراردادی', 'قراردادی')], default='پروژه ای', max_length=100)),
                ('akharin_maghta_tahsili', models.CharField(max_length=100)),
                ('akharin_reshte_tahsili', models.CharField(max_length=150)),
                ('sazman_parvane_behzisti', models.CharField(choices=[('سازمان نظام روانشناسی', 'سازمان نظام روانشناسی'), ('پروانه اشتغال تخصصی', 'پروانه اشتغال تخصصی'), ('بهزیستی', 'بهزیستی'), ('ندارد', 'ندارد')], default='ندارد', max_length=150)),
                ('tarikh_shoro_faliyat', models.DateTimeField(auto_now_add=True)),
                ('roozhaye_hozor', models.CharField(blank=True, max_length=250, null=True)),
                ('pedar_name', models.CharField(blank=True, max_length=250, null=True)),
                ('birthday', models.DateTimeField()),
                ('shaba_number', models.CharField(blank=True, max_length=250, null=True)),
                ('hesab_number', models.IntegerField(default=0)),
                ('molahezat', models.TextField(blank=True, max_length=9000, null=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.city')),
                ('daneshkadeh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.daneshkadeh')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMarkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('meli_code', models.IntegerField(blank=True, unique=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('markaz_moshavere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moshavere.marakezmoshavere')),
            ],
        ),
    ]
