# Generated by Django 4.0.2 on 2022-05-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moshavere', '0006_alter_nobat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nobat',
        ),
        migrations.AddField(
            model_name='nobat',
            name='daneshjoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nobat',
            name='moshaver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moshavere.moshaverprofile'),
        ),
    ]
