# Generated by Django 4.0.2 on 2022-05-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0007_remove_reservation_nobat_nobat_daneshjoo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nobat',
            old_name='days',
            new_name='day',
        ),
    ]
