# Generated by Django 4.0.2 on 2022-05-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0008_rename_days_nobat_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nobat',
            name='day',
        ),
        migrations.AddField(
            model_name='nobat',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moshavere.days'),
        ),
    ]
