# Generated by Django 4.0.2 on 2022-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0009_remove_nobat_day_nobat_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nobat',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
