# Generated by Django 4.0.2 on 2022-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0011_reservation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tarikh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
