# Generated by Django 4.0.2 on 2022-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0013_remove_nobat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulation',
            name='daneshjoo_first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='consulation',
            name='daneshjoo_last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='consulation',
            name='daneshjoo_meli_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='consulation',
            name='daneshjoo_student_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='consulation',
            name='tedad_jalasat_moshavere',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consulation',
            name='arzyabi',
            field=models.CharField(max_length=200),
        ),
    ]
