# Generated by Django 4.0.2 on 2022-05-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0015_consulation_erja_ravanpezeshk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulation',
            name='hozor',
        ),
    ]
