# Generated by Django 4.0.2 on 2022-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0016_remove_consulation_hozor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulation',
            name='moshkel_feli',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='consulation',
            name='moshkel_asli',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
