# Generated by Django 4.0.2 on 2022-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0017_consulation_moshkel_feli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
