# Generated by Django 4.0.2 on 2022-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0018_consulation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulation',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
