# Generated by Django 4.0.2 on 2022-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0021_time_remove_reservation_time_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='times',
            field=models.ManyToManyField(blank=True, to='moshavere.Time'),
        ),
    ]
