# Generated by Django 4.0.2 on 2022-05-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0023_remove_reservation_time_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulation',
            name='daneshjoo_student_number',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
