# Generated by Django 4.0.2 on 2022-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0024_alter_consulation_daneshjoo_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='student_number',
            field=models.CharField(max_length=50),
        ),
    ]
