# Generated by Django 4.0.2 on 2022-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0025_alter_reservation_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='student_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
