# Generated by Django 4.0.5 on 2022-06-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0026_alter_reservation_student_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nazer',
        ),
    ]
